---

image:
  name: pandoc/core:latest-alpine
  entrypoint: ["/bin/sh", "-c"]

pages:
  stage: deploy
  script:
    - apk update
    - apk add wget make git graphviz py3-pip
    - pip install pandoc-include
    - git submodule update --init
    - cp config/tufte/* .
    - git submodule add https://github.com/p2pcollab/tufte-css pub/tufte-css
    - git submodule add https://github.com/p2pcollab/tufte-pandoc-css pub/tufte-pandoc-css
    - make
    - mv public/README.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
